#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name=084
#SBATCH --output=data/slurm_logs/084.out
#SBATCH --error=data/slurm_logs/084.err
#SBATCH --time=24:00:00
#SBATCH --mem=36000
#SBATCH --gres=gpu:1
#SBATCH --qos=medium
#SBATCH --nodelist=noether,gauss

srun -u /slurm-storage/leobuj/.conda/envs/leobuj-env/bin/python -m exp.coordvit_cifar100 \
    --model-description coordvit-no-wd --num-exp 1 \
    --image-size 32 --patch-size 8 \
    --num-epochs 200 --early-stopping 200 --lr 1e-6 --batch-size 32 \
    --weight-decay 0 --dropout 0.2 \
    --num-heads 12 --num-layers 12 --mlp-size 3072 --embed-size 768 --hidden-size 768