#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name=027
#SBATCH --output=data/slurm_logs/027.out
#SBATCH --error=data/slurm_logs/027.err
#SBATCH --time=24:00:00
#SBATCH --mem=36000
#SBATCH --gres=gpu:1
#SBATCH --qos=medium
#SBATCH --nodelist=noether

srun -u /slurm-storage/leobuj/.conda/envs/leobuj-env/bin/python -m exp.vit_cifar100 \
    --model-description large_vit --num-exp 1 \
    --image-size 32 --patch-size 8 \
    --num-epochs 200 --early-stopping 200 --lr 5e-05 --batch-size 256 \
    --weight-decay 0.0 --dropout 0.2 \
    --num-heads 16 --num-layers 24 --mlp-size 4096 --embed-size 1024 --hidden-size 1024