#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name=057
#SBATCH --output=data/slurm_logs/057.out
#SBATCH --error=data/slurm_logs/057.err
#SBATCH --time=24:00:00
#SBATCH --mem=36000
#SBATCH --gres=gpu:1
#SBATCH --qos=medium
#SBATCH --nodelist=noether

srun -u /slurm-storage/leobuj/.conda/envs/leobuj-env/bin/python -m exp.pgat_cifar100 \
    --model-description pgat-sin-256 --batch-size 32 \
    --num-gat-layers 2 --hidden-size 256 --num-heads 8 \
    --pe sinusoidal --sinusoidal-size 256