#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name=078
#SBATCH --output=data/slurm_logs/078.out
#SBATCH --error=data/slurm_logs/078.err
#SBATCH --time=24:00:00
#SBATCH --mem=36000
#SBATCH --gres=gpu:1
#SBATCH --qos=medium
#SBATCH --nodelist=noether,gauss

srun -u /slurm-storage/leobuj/.conda/envs/leobuj-env/bin/python -m exp.spgat_cifar100 \
    --model-description lrgb-pe-256 --batch-size 32 \
    --pe 1 --sp-agg lrgb --channel-size 12 --early-stopping 200