#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name=006
#SBATCH --output=data/slurm_logs/006.out
#SBATCH --error=data/slurm_logs/006.err
#SBATCH --time=10:00:00
#SBATCH --mem=36000
#SBATCH --gres=gpu:1
#SBATCH --qos=medium

srun -u /slurm-storage/leobuj/.conda/envs/leobuj-env/bin/python -m exp.vit_cifar100 --num-exp 1 --model-description small_vit --batch-size 512 --dropout 0.2 --early-stopping 200 --embed-size 768 --hidden-size 768 --image-size 32 --lr 0.00005 --mlp-size 3072 --num-epochs 200 --num-heads 12 --num-layers 12 --patch-size 8 --weight-decay 0.0001
